//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMCM {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rsc_Q1040_B1_2_5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsc_Q1040_B1_2_5() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMCM.rsc_Q1040_B1_2.5", typeof(rsc_Q1040_B1_2_5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DslCpeConfig version=&quot;3.0&quot;&gt;
        ///  &lt;InternetGatewayDevice&gt;
        ///    &lt;LANDeviceNumberOfEntries&gt;1&lt;/LANDeviceNumberOfEntries&gt;
        ///    &lt;WANDeviceNumberOfEntries&gt;2&lt;/WANDeviceNumberOfEntries&gt;
        ///    &lt;DeviceInfo&gt;
        ///      &lt;FirstUseDate&gt;0001-01-01T00:00:00Z&lt;/FirstUseDate&gt;
        ///      &lt;VendorConfigFileNumberOfEntries&gt;0&lt;/VendorConfigFileNumberOfEntries&gt;
        ///    &lt;/DeviceInfo&gt;
        ///    &lt;X_BROADCOM_COM_LoginCfg&gt;
        ///      &lt;AdminPassword&gt;YWRtaW4A&lt;/AdminPassword&gt;
        ///    &lt;/X_BROADCOM_COM_LoginCfg&gt;
        ///    &lt;X_BROADCOM_COM_EthernetSwitch&gt;
        ///      &lt;N [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoA_1 {
            get {
                return ResourceManager.GetString("PPPoA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Username&gt;
        ///          &lt;Password&gt;.
        /// </summary>
        internal static string PPPoA_2 {
            get {
                return ResourceManager.GetString("PPPoA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Password&gt;
        ///          &lt;X_CUSTOM_PppMtu&gt;1500&lt;/X_CUSTOM_PppMtu&gt;
        ///          &lt;X_BROADCOM_COM_IfName&gt;pppoa0&lt;/X_BROADCOM_COM_IfName&gt;
        ///          &lt;PortMappingNumberOfEntries&gt;0&lt;/PortMappingNumberOfEntries&gt;
        ///        &lt;/WANPPPConnection&gt;
        ///        &lt;WANPPPConnection nextInstance=&quot;2&quot; &gt;&lt;/WANPPPConnection&gt;
        ///      &lt;/WANConnectionDevice&gt;
        ///      &lt;WANConnectionDevice nextInstance=&quot;5&quot; &gt;&lt;/WANConnectionDevice&gt;
        ///    &lt;/WANDevice&gt;
        ///    &lt;WANDevice instance=&quot;3&quot;&gt;
        ///      &lt;WANConnectionNumberOfEntries&gt;0&lt;/WANConnectionNumberOfEntries&gt;
        ///      &lt;WANCom [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoA_3 {
            get {
                return ResourceManager.GetString("PPPoA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DslCpeConfig version=&quot;3.0&quot;&gt;
        ///  &lt;InternetGatewayDevice&gt;
        ///    &lt;LANDeviceNumberOfEntries&gt;1&lt;/LANDeviceNumberOfEntries&gt;
        ///    &lt;WANDeviceNumberOfEntries&gt;2&lt;/WANDeviceNumberOfEntries&gt;
        ///    &lt;DeviceInfo&gt;
        ///      &lt;FirstUseDate&gt;0001-01-01T00:00:00Z&lt;/FirstUseDate&gt;
        ///      &lt;VendorConfigFileNumberOfEntries&gt;0&lt;/VendorConfigFileNumberOfEntries&gt;
        ///    &lt;/DeviceInfo&gt;
        ///    &lt;X_BROADCOM_COM_LoginCfg&gt;
        ///      &lt;AdminPassword&gt;YWRtaW4A&lt;/AdminPassword&gt;
        ///    &lt;/X_BROADCOM_COM_LoginCfg&gt;
        ///    &lt;X_BROADCOM_COM_EthernetSwitch&gt;
        ///      &lt;N [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoA_TV_1 {
            get {
                return ResourceManager.GetString("PPPoA_TV_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Username&gt;
        ///          &lt;Password&gt;.
        /// </summary>
        internal static string PPPoA_TV_2 {
            get {
                return ResourceManager.GetString("PPPoA_TV_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Password&gt;
        ///          &lt;X_CUSTOM_PppMtu&gt;1500&lt;/X_CUSTOM_PppMtu&gt;
        ///          &lt;X_BROADCOM_COM_IfName&gt;pppoa0&lt;/X_BROADCOM_COM_IfName&gt;
        ///          &lt;PortMappingNumberOfEntries&gt;0&lt;/PortMappingNumberOfEntries&gt;
        ///        &lt;/WANPPPConnection&gt;
        ///        &lt;WANPPPConnection nextInstance=&quot;2&quot; &gt;&lt;/WANPPPConnection&gt;
        ///      &lt;/WANConnectionDevice&gt;
        ///      &lt;WANConnectionDevice instance=&quot;5&quot;&gt;
        ///        &lt;WANIPConnectionNumberOfEntries&gt;1&lt;/WANIPConnectionNumberOfEntries&gt;
        ///        &lt;WANPPPConnectionNumberOfEntries&gt;0&lt;/WANPPPConnectionNumberOfEntries&gt;
        ///    [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoA_TV_3 {
            get {
                return ResourceManager.GetString("PPPoA_TV_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DslCpeConfig version=&quot;3.0&quot;&gt;
        ///  &lt;InternetGatewayDevice&gt;
        ///    &lt;LANDeviceNumberOfEntries&gt;2&lt;/LANDeviceNumberOfEntries&gt;
        ///    &lt;WANDeviceNumberOfEntries&gt;1&lt;/WANDeviceNumberOfEntries&gt;
        ///    &lt;DeviceInfo&gt;
        ///      &lt;FirstUseDate&gt;0001-01-01T00:00:00Z&lt;/FirstUseDate&gt;
        ///      &lt;VendorConfigFileNumberOfEntries&gt;0&lt;/VendorConfigFileNumberOfEntries&gt;
        ///    &lt;/DeviceInfo&gt;
        ///    &lt;X_BROADCOM_COM_LoginCfg&gt;
        ///      &lt;AdminPassword&gt;YWRtaW4A&lt;/AdminPassword&gt;
        ///    &lt;/X_BROADCOM_COM_LoginCfg&gt;
        ///    &lt;X_BROADCOM_COM_EthernetSwitch&gt;
        ///      &lt;N [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoA_TV_Group_1 {
            get {
                return ResourceManager.GetString("PPPoA_TV_Group_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Username&gt;
        ///          &lt;Password&gt;.
        /// </summary>
        internal static string PPPoA_TV_Group_2 {
            get {
                return ResourceManager.GetString("PPPoA_TV_Group_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Password&gt;
        ///          &lt;X_CUSTOM_PppMtu&gt;1500&lt;/X_CUSTOM_PppMtu&gt;
        ///          &lt;X_BROADCOM_COM_IfName&gt;pppoa0&lt;/X_BROADCOM_COM_IfName&gt;
        ///          &lt;ExternalIPAddress notification=&quot;2&quot;&gt;(null)&lt;/ExternalIPAddress&gt;
        ///          &lt;PortMappingNumberOfEntries&gt;0&lt;/PortMappingNumberOfEntries&gt;
        ///        &lt;/WANPPPConnection&gt;
        ///        &lt;WANPPPConnection nextInstance=&quot;2&quot; &gt;&lt;/WANPPPConnection&gt;
        ///      &lt;/WANConnectionDevice&gt;
        ///      &lt;WANConnectionDevice instance=&quot;5&quot;&gt;
        ///        &lt;WANIPConnectionNumberOfEntries&gt;1&lt;/WANIPConnectionNumberOfEntries&gt;
        ///        [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoA_TV_Group_3 {
            get {
                return ResourceManager.GetString("PPPoA_TV_Group_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DslCpeConfig version=&quot;3.0&quot;&gt;
        ///  &lt;InternetGatewayDevice&gt;
        ///    &lt;LANDeviceNumberOfEntries&gt;1&lt;/LANDeviceNumberOfEntries&gt;
        ///    &lt;WANDeviceNumberOfEntries&gt;2&lt;/WANDeviceNumberOfEntries&gt;
        ///    &lt;DeviceInfo&gt;
        ///      &lt;FirstUseDate&gt;0001-01-01T00:00:00Z&lt;/FirstUseDate&gt;
        ///      &lt;VendorConfigFileNumberOfEntries&gt;0&lt;/VendorConfigFileNumberOfEntries&gt;
        ///    &lt;/DeviceInfo&gt;
        ///    &lt;X_BROADCOM_COM_LoginCfg&gt;
        ///      &lt;AdminPassword&gt;YWRtaW4A&lt;/AdminPassword&gt;
        ///    &lt;/X_BROADCOM_COM_LoginCfg&gt;
        ///    &lt;X_BROADCOM_COM_EthernetSwitch&gt;
        ///      &lt;N [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoE_1 {
            get {
                return ResourceManager.GetString("PPPoE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Username&gt;
        ///          &lt;Password&gt;.
        /// </summary>
        internal static string PPPoE_2 {
            get {
                return ResourceManager.GetString("PPPoE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/Password&gt;
        ///          &lt;X_BROADCOM_COM_IfName&gt;ppp0&lt;/X_BROADCOM_COM_IfName&gt;
        ///          &lt;X_BROADCOM_COM_AddPppToBridge&gt;TRUE&lt;/X_BROADCOM_COM_AddPppToBridge&gt;
        ///          &lt;PortMappingNumberOfEntries&gt;0&lt;/PortMappingNumberOfEntries&gt;
        ///        &lt;/WANPPPConnection&gt;
        ///        &lt;WANPPPConnection nextInstance=&quot;2&quot; &gt;&lt;/WANPPPConnection&gt;
        ///      &lt;/WANConnectionDevice&gt;
        ///      &lt;WANConnectionDevice nextInstance=&quot;5&quot; &gt;&lt;/WANConnectionDevice&gt;
        ///    &lt;/WANDevice&gt;
        ///    &lt;WANDevice instance=&quot;3&quot;&gt;
        ///      &lt;WANConnectionNumberOfEntries&gt;0&lt;/WANConnectionNumb [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PPPoE_3 {
            get {
                return ResourceManager.GetString("PPPoE_3", resourceCulture);
            }
        }
    }
}
